--USE DDLCOMMANDS;
--GO


--CREATING EMPLOYEES TABLE
/*CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID INT,  
    FIRST_NAME VARCHAR(50),  
    LAST_NAME VARCHAR(50),  
    SALARY DECIMAL(10,2),  
    DEPARTMENT_ID INT  
);*/

/*INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID) 
VALUES 
(101, 'Sathish', 'Kumar', 45000.00, 1),
(102, 'Sanjana', 'Balaji', 69000.00, 2),
(103, 'Suresh', 'Kumar', 55000.00, 1),
(104, 'Nandhini', 'Ramesh', 70000.00, 3);*/

--SELECT * FROM EMPLOYEES;


--CREATING DEPARTMENTS TABLE

/*CREATE TABLE DEPARTMENTS (
    DEPARTMENT_ID INT,  
    DEPARTMENT_NAME VARCHAR(50),  
    LOCATION VARCHAR(50),  
    MANAGER_NAME VARCHAR(50)  
);*/
/*INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION, MANAGER_NAME) 
VALUES 
(1, 'Marketting', 'Coimbatore', 'Saravanan'),
(2, 'Finance', 'Chennai', 'Gopinath'),
(3, 'IT', 'Vellore', 'Gayathri');*/

--SELECT * FROM DEPARTMENTS;


--TASK-1 [Create the TRG_DEPT Table]

/*CREATE TABLE TRG_DEPT (
    ID INT,  
    NAME VARCHAR(25)  
);*/
--SELECT * FROM TRG_DEPT;



--TASK-2 [Populate DEPT101 with data from DEPARTMENTS]

/*SELECT DEPARTMENT_ID AS ID, DEPARTMENT_NAME AS NAME 
INTO DEPT101 
FROM DEPARTMENTS;*/
--SELECT *FROM DEPT101;



--3. Create the TRG_EMP Table

/*CREATE TABLE TRG_EMP (
    ID INT,  
    LAST_NAME VARCHAR(25),  
    FIRST_NAME VARCHAR(25),  
    DEPT_ID INT  
);*/
--SELECT * FROM TRG_EMP;

--4. Modify TRG_EMP to allow longer LAST_NAME

--ALTER TABLE TRG_EMP ALTER COLUMN LAST_NAME VARCHAR(50);
--EXEC sp_help 'TRG_EMP';



--5. Create TRG_EMPLOYEES based on EMPLOYEES

/*SELECT EMPLOYEE_ID AS ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID AS DEPT_ID 
INTO TRG_EMPLOYEES 
FROM EMPLOYEES;*/

--SELECT * FROM TRG_EMPLOYEES;



--6. Drop TRG_EMP Table

--DROP TABLE TRG_EMP;
--SELECT * FROM TRG_EMP;



--7. Rename TRG_EMPLOYEES to TRG_EMP

--EXEC sp_rename 'TRG_EMPLOYEES', 'TRG_EMP';
--SELECT * FROM TRG_EMP;


--8. Drop FIRST_NAME Column from TRG_EMP

--ALTER TABLE TRG_EMP DROP COLUMN FIRST_NAME;
--EXEC sp_help 'TRG_EMP';








